#!/usr/bin/env ansible-playbook
#
# This playbook will gracefully remove an existing member from a load balancer
# pool.
# It first sets the weight of the member to 0, this will prevent the member
# accepting further connections.
# It then waits for the number of minutes set by the 'pause_duration' variable.
# Once this time has elapsed it will remove the member from the pool and then
# display the remaining pool members
#
# Usage:
# source openrc
# ansible-playbook drop_member_from_lb_pool.yaml
#
# or if wanting to override variables in the playbook
# ansible-playbook drop_member_from_lb_pool.yaml -e "lb_pool_name=http_pool lb_member_name=member_1 pause_duration=2"
#
---
- name: Create loadbalancer and add a simple webserver
  hosts: localhost

  vars:
    lb_name: lb_test
    lb_pool_name: http_pool
    lb_member_name: member_2
    pause_duration: 60

  tasks:

    - name: Disable member in pool, set member weight to zero
      shell: openstack loadbalancer member set {{ lb_pool_name }} {{ lb_member_name }} --weight 0

    - name: Wait for current load balancer connections to complete
      pause:
        minutes: "{{ pause_duration }}"

    - name: remove member from pool
      shell: openstack loadbalancer member delete {{ lb_pool_name }} {{ lb_member_name }}

    - name: Retrieve current pool members
      shell: openstack loadbalancer member list "{{ lb_pool_name }}" -f json
      register: lb_pool_state

    - name: List current members
      debug:
        # msg: "Outputs {{ item }}"
        msg: "pool member ==> {{ item.name }}"
      with_items: "{{ lb_pool_state.stdout | from_json }}"
