#!/usr/bin/env ansible-playbook

- name: Cookbook to demonstrate looping over dicts
  hosts: localhost
  vars:
    key_host: master1
    instances:
      master1:
        instance_name: master1
        instance_group: master-nodes
        flavor: c1.c4r4
      worker1:
        instance_name: worker1
        instance_group: worker-nodes
        flavor: c1.c1r1
      worker2:
        instance_name: worker2
        instance_group: worker-nodes
        flavor: c1.c1r1
      worker3:
        instance_name: worker3
        instance_group: worker-nodes
        flavor: c1.c1r1
      worker4:
        instance_name: worker4
        instance_group: worker-nodes
        flavor: c1.c1r1

  tasks:
    - name: Loop over dict
      debug:
        msg: "Host {{ item.key }} flavor = {{ item.value.flavor }}"
      with_dict: "{{ instances }}"

    - name: Loop over dict with conditional
      debug:
        msg: "Host {{ item.key }} flavor = {{ item.value.flavor }}"
      when: item.value.flavor == 'c1.c4r4'
      with_dict: "{{ instances }}"

    - name: Reference a specific value using a key from a variable
      debug:
        msg: "Host {{ key_host }} flavor = {{ instances[key_host]['flavor'] }}"
